# Generated by Django 4.2.3 on 2023-08-14 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_info',
            field=models.CharField(default='Неизвестно', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'DOLLAR'), ('RUB', 'RUBLIES')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
