# Generated by Django 4.2.3 on 2023-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_book_book_info_book_currency_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email_author',
            field=models.EmailField(default='sugar_daddy228@yandex.ru', max_length=254),
        ),
    ]
