# Generated by Django 4.2.3 on 2023-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
