# Generated by Django 4.2.3 on 2023-08-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_author_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BookAuthor',
        ),
    ]
