# Generated by Django 4.2.3 on 2023-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_remove_bookauthor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
