# Generated by Django 4.2.3 on 2023-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_alter_bookauthor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
