# Generated by Django 4.2.3 on 2023-08-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_bookauthor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='slug',
        ),
    ]
