# Generated by Django 4.2.3 on 2023-08-15 08:36

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_bookauthor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='slug',
            field=models.SlugField(default=builtins.id),
        ),
    ]
