# Generated by Django 4.2.3 on 2023-08-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0021_alter_bookauthor_id_alter_bookauthor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
